# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "minitest", "~> 5.25"
  gem "rack", ">= 2.2"
  gem "rake", "~> 13.0"
  gem "rubocop", "~> 1.80", require: false
  gem "rubocop-minitest", "~> 0.38", require: false
  gem "sidekiq", ">= 7.0"
end
